An error happened during execution:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/tmp0olbxo_7.py", line 51, in main
    intersection_area = compute_polygon_circle_intersection_area(triangle, circle_center, R_float)
  File "/tmp/tmp0olbxo_7.py", line 100, in compute_polygon_circle_intersection_area
    from shapely.geometry import Polygon, LineString, Point
ModuleNotFoundError: No module named 'shapely'
